### ISSUE TITLE
Feature request Hide servers, where player hasnt permission in /server list

### ISSUE THREAD

**Issue by pjindras** [4drian3d/ServerPermissions#37] opened 2024-08-09 08:31 UTC
Hello, it would be nice, if someone types /server to show him only servers, where the player has permission.

![image](https://github.com/user-attachments/assets/5e56f30a-4515-4b48-b8df-f038e1d3fc0e)

**Comment by 4drian3d** [comment] 2024-11-11 14:38
duplicate of #16

**Closed as duplicate by 4drian3d** 2024-11-11 14:38 UTC
